#ci/cd with the help of github actions

name: CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "helm/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build
        run: go build -o go-static-app

      - name: test
        run: go test ./...

  code-quality:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.56.2
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/go-web-app:${{github.run_id}}

  updating-image-tag-in-helm-values:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-static-application/values.yaml

      - name: commit changes
        run: |
          git config --global user.email "pranayreddy.k12@gmail.com"
          git config --global user.name "PranayReddy-K"
          git add helm/go-static-application/values.yaml
          git commit -m "Update image tag in Helm chart"
          git push
